darkmode: true

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Andrea Baccin
title: Software Lead Engineer
email: baccin.andrea@gmail.com
website: www.github.com/sproogen/resume-theme

# Social links
twitter_username: abaccin
github_username:  abaccin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: chillwildlife
linkedin_username: jameswgrant
# pinterest_username: jekyll
youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
	I am a computer engineer and .net enthusiasm with over a decade of experience in designing and developing distributed software systems. I have experience in leading, organizing and successfully accomplishing software projects with rich set of features and functionality. Especially, I have been successful inbending abstract system requirements into real software solutions having high security and performance. With strong communication, team cooperation, programming and mentoring capabilities.	
  skills: <mark>AWS</mark> <mark>.net</mark> <mark>Domain Driven Design</mark> <mark>Distributed Systems</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
   - Rock climbing
   - Gaming
   - Knitting
   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
