darkmode: true

# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Personal info
name: Andrea Baccin
title: Software Lead Engineer
email: baccin.andrea@gmail.com
website: https://github.com/abaccin

# Social links
twitter_username: abaccin
github_username:  abaccin
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
instagram_username: andrea.baccin.photo
linkedin_username: baccin
# pinterest_username: jekyll
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I am a computer engineer and .net enthusiast with over a decade of experience in designing and developing distributed software systems. I have experience in leading, organizing and successfully accomplishing software projects with rich set of features and functionality. Especially, I have been successful inbending abstract system requirements into real software solutions having high security and performance. With strong communication, team cooperation, programming and mentoring capabilities.	
  
  Skills: <mark>AWS</mark> <mark>.net</mark> <mark>Domain Driven Design</mark> <mark>Distributed Systems</mark>  <mark>SOLID</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Home Automation: currently I am building my home automation system based on open source software and standard protocols with all resources running locally within the perimeter of the house and not requiring to access resources online.
  HP Calculators: I am a huge fan on HP Calculator and evangelist of RPN. I have been country moderator for the Italian forum and contributor of hpcalc.org website.
  Photography: Nikon user before digital era, currently shooting with a D750 full frame dslr.
  
# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
